In [4]:
import pandas as pd
import dotenv
import openai
import os
from functools import lru_cache


pd.options.display.max_colwidth = 300

In [5]:
titles = (
    "The Dark Knight",
    "Forrest Gump",
    "Interstellar",
    "Joker",
    "Lion King",
    "Lord Of The Rings",
    "The Good, The Bad And The Ugly",
    "WALL-E",
)

In [6]:
plots = (
    "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
    "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.",
    "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
    "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
    "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
)

In [7]:
df = pd.DataFrame({
    'titles': titles,
    'plots': plots,
})

In [8]:
df

,titles,plots
0,The Dark Knight,"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
1,Forrest Gump,"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart."
2,Interstellar,A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.
3,Joker,"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker."
4,Lion King,"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."
5,Lord Of The Rings,A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.
6,"The Good, The Bad And The Ugly",A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.
7,WALL-E,"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."

In [9]:
dotenv.load_dotenv(override=True)
openai.api_key = os.getenv("OPENAI_API_KEY")

In [68]:
response = openai.Engine("babbage").search(
    documents=plots, 
    query="adventure",
    max_rerank=None,
    return_metadata=True
)

scores = [x["score"] for x in response["data"]]

df_scores = pd.DataFrame({
    'scores': scores,
    'titles': titles,
    'plots': plots,
})

df_scores.sort_values(by='scores', ascending=False)

,scores,titles,plots
2,186.287,Interstellar,A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.
6,180.562,"The Good, The Bad And The Ugly",A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.
5,151.416,Lord Of The Rings,A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.
0,123.131,The Dark Knight,"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
7,120.461,WALL-E,"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."
3,56.160,Joker,"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker."
1,-22.211,Forrest Gump,"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart."
4,-44.982,Lion King,"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."

In [10]:
@lru_cache
def search(docs, query, engine):
    response = openai.Engine(engine).search(
        documents=docs, 
        query=query,
        max_rerank=None,
        return_metadata=True
    )

    scores = [x["score"] for x in response["data"]]

    df_scores = pd.DataFrame({
        'scores': scores,
        'titles': titles,
        'plots': plots,
    })
    
    return df_scores.sort_values(by='scores', ascending=False)

In [128]:
search(docs=plots, query="galactic adventure", engine="babbage")

,scores,titles,plots
2,258.534,Interstellar,A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.
7,189.421,WALL-E,"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."
5,34.757,Lord Of The Rings,A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.
6,19.609,"The Good, The Bad And The Ugly",A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.
1,-11.491,Forrest Gump,"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart."
4,-48.943,Lion King,"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."
3,-64.154,Joker,"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker."
0,-82.181,The Dark Knight,"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."

In [134]:
search(docs=plots, query="galaactic adventure", engine="babbage")

,scores,titles,plots
2,107.340,Interstellar,A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.
7,87.738,WALL-E,"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."
4,31.357,Lion King,"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."
5,28.566,Lord Of The Rings,A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.
0,26.383,The Dark Knight,"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
6,10.879,"The Good, The Bad And The Ugly",A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.
3,-42.269,Joker,"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker."
1,-45.701,Forrest Gump,"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart."

In [75]:
search(docs=plots, query="anti-hero", engine="babbage")

,scores,titles,plots
3,151.436,Joker,"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker."
0,111.372,The Dark Knight,"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
7,48.095,WALL-E,"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."
5,33.026,Lord Of The Rings,A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.
2,28.302,Interstellar,A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.
6,20.940,"The Good, The Bad And The Ugly",A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.
4,-2.525,Lion King,"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."
1,-10.453,Forrest Gump,"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart."

In [93]:
search(docs=plots, query="Joker is main antagonist", engine="babbage")

,scores,titles,plots
0,265.475,The Dark Knight,"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
3,226.316,Joker,"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker."
7,-21.928,WALL-E,"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."
5,-35.400,Lord Of The Rings,A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.
1,-43.277,Forrest Gump,"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart."
2,-56.194,Interstellar,A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.
4,-63.975,Lion King,"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."
6,-72.123,"The Good, The Bad And The Ugly",A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.

In [94]:
search(docs=plots, query="Joker is main protagonist", engine="babbage")

,scores,titles,plots
3,216.214,Joker,"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker."
0,211.835,The Dark Knight,"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
7,9.634,WALL-E,"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."
1,-19.030,Forrest Gump,"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart."
2,-29.062,Interstellar,A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.
5,-29.447,Lord Of The Rings,A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.
6,-54.575,"The Good, The Bad And The Ugly",A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.
4,-79.247,Lion King,"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."

In [102]:
search(docs=plots, query="animation", engine="babbage")

,scores,titles,plots
7,179.293,WALL-E,"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."
3,124.201,Joker,"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker."
4,123.181,Lion King,"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."
0,19.751,The Dark Knight,"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
2,-10.880,Interstellar,A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.
5,-17.456,Lord Of The Rings,A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.
1,-34.404,Forrest Gump,"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart."
6,-132.470,"The Good, The Bad And The Ugly",A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.

In [103]:
search(docs=plots, query="Todd Phillips", engine="babbage")

,scores,titles,plots
3,200.841,Joker,"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker."
0,161.501,The Dark Knight,"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
6,70.775,"The Good, The Bad And The Ugly",A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.
1,28.408,Forrest Gump,"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart."
7,16.220,WALL-E,"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."
5,-54.336,Lord Of The Rings,A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.
2,-57.425,Interstellar,A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.
4,-65.302,Lion King,"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."

In [115]:
search(docs=plots, query="Peter Jackson", engine="babbage")

,scores,titles,plots
5,411.571,Lord Of The Rings,A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.
2,156.979,Interstellar,A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.
7,114.953,WALL-E,"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."
4,73.764,Lion King,"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."
3,59.667,Joker,"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker."
6,59.407,"The Good, The Bad And The Ugly",A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.
0,48.632,The Dark Knight,"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
1,-28.446,Forrest Gump,"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart."

In [116]:
search(docs=plots, query="David Lynch", engine="babbage")

,scores,titles,plots
3,103.324,Joker,"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker."
7,66.325,WALL-E,"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."
0,48.897,The Dark Knight,"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
1,46.968,Forrest Gump,"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart."
2,30.245,Interstellar,A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.
6,19.881,"The Good, The Bad And The Ugly",A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.
5,-50.690,Lord Of The Rings,A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.
4,-80.201,Lion King,"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."

In [117]:
search(docs=plots, query="a movie which will make me cry", engine="babbage")

,scores,titles,plots
7,26.843,WALL-E,"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."
3,16.733,Joker,"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker."
5,13.041,Lord Of The Rings,A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.
1,12.284,Forrest Gump,"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart."
0,9.056,The Dark Knight,"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
2,3.259,Interstellar,A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.
6,-0.522,"The Good, The Bad And The Ugly",A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.
4,-9.176,Lion King,"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."

In [12]:
search(docs=plots, query="WALL-E", engine="babbage")

,scores,titles,plots
7,152.538,WALL-E,"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."
2,114.950,Interstellar,A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.
4,110.747,Lion King,"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."
3,51.633,Joker,"In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker."
0,50.328,The Dark Knight,"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
1,41.026,Forrest Gump,"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart."
6,26.024,"The Good, The Bad And The Ugly",A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.
5,15.681,Lord Of The Rings,A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.

In [144]:
search(docs=plots, query="a"*8000, engine="ada")

InvalidRequestError: The document at index 4 is 17 tokens over the length limit of 35. If you would like us to add a feature to auto-truncate server-side, let us know at support@openai.com.

### You can also use it for classification tasks

In [41]:
directors = (
    "Christopher Nolan",
    "George Lucas",
    "David Lyunch",
    "Peter Jackson",
    "Steven Spielberg",
    "Riddleey Scott",
    "James Cameron",
#     "The director"
)

In [42]:
response = openai.Engine("babbage").search(
    documents=directors, 
    query="The director of Jaws",
    max_rerank=None,
    return_metadata=True
)

scores = [x["score"] for x in response["data"]]

df_scores = pd.DataFrame({
    'scores': scores,
    'directors': directors,
})

df_scores.sort_values(by='scores', ascending=False)

    scores          directors
4  233.068   Steven Spielberg
6  154.350      James Cameron
1  149.984       George Lucas
0  119.999  Christopher Nolan
3   70.305      Peter Jackson
5   57.364     Riddleey Scott
2    9.613       David Lyunch